# Generated by Django 4.1 on 2022-08-14 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 18, 4, 1, 103710)),
        ),
    ]
