# Generated by Django 4.1 on 2022-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
