# Generated by Django 4.1.3 on 2022-11-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bids_auction_id_remove_watchlist_auction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='noOfBids',
        ),
    ]
