# Generated by Django 4.1.3 on 2022-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bids_currentbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
