# Generated by Django 4.1.3 on 2022-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctions_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
