# Generated by Django 4.1.3 on 2022-12-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctions_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('comment', models.CharField(max_length=5000)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CMauction', to='auctions.auctions')),
            ],
        ),
    ]
