# Generated by Django 4.1 on 2022-08-14 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=5000)),
                ('startbid', models.IntegerField()),
                ('category', models.CharField(default='', max_length=64)),
                ('image', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 14, 18, 3, 41, 208037))),
            ],
        ),
    ]
