# Generated by Django 4.1 on 2022-08-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
