# Generated by Django 4.1.3 on 2022-11-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctions_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBid', models.IntegerField(default=0)),
                ('currentBidder', models.CharField(max_length=64)),
                ('noOfBids', models.IntegerField(default=0)),
            ],
        ),
    ]
