# Generated by Django 4.1.3 on 2022-11-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctions_startbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='bidauction', to='auctions.auctions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='WLauction', to='auctions.auctions'),
            preserve_default=False,
        ),
    ]
