# Generated by Django 4.1.3 on 2022-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctions_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='username',
            field=models.TextField(default='', max_length=64),
        ),
    ]
