# Generated by Django 4.2 on 2023-04-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=5000)),
                ('time', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
