# Generated by Django 4.2.3 on 2023-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
