# Generated by Django 4.2.3 on 2023-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_user_follower_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
