# Generated by Django 4.2.3 on 2023-08-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_alter_post_likes_alter_user_follower_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.CharField(max_length=64),
        ),
    ]
