# Generated by Django 4.2.3 on 2023-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_alter_user_follower_alter_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.JSONField(),
        ),
    ]
