# Generated by Django 4.2.4 on 2023-09-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_alter_user_follower_alter_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
