# Generated by Django 4.2.4 on 2023-09-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0010_post_userliked_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="userLiked",
            field=models.CharField(max_length=64),
        ),
    ]
