# Generated by Django 4.2.4 on 2023-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0012_alter_post_userliked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="userLiked",
            field=models.JSONField(default={"peopleLiked": []}),
        ),
    ]
