# Generated by Django 4.2.5 on 2023-09-27 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0013_alter_post_userliked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="userLiked",
        ),
    ]
