# Generated by Django 4.1.4 on 2023-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('uri', models.CharField(max_length=64)),
                ('albumUrl', models.CharField(max_length=64)),
            ],
        ),
    ]
